package Models.Corba;


/**
* Models/Corba/ICenterServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Friday, October 19, 2018 1:05:36 o'clock PM EDT
*/

public interface ICenterServer extends ICenterServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICenterServer
