package Models.Corba;

/**
* Models/Corba/ICenterServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Friday, October 19, 2018 1:05:36 o'clock PM EDT
*/

public final class ICenterServerHolder implements org.omg.CORBA.portable.Streamable
{
  public Models.Corba.ICenterServer value = null;

  public ICenterServerHolder ()
  {
  }

  public ICenterServerHolder (Models.Corba.ICenterServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Models.Corba.ICenterServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Models.Corba.ICenterServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Models.Corba.ICenterServerHelper.type ();
  }

}
