package Models.Corba;

/**
* Models/Corba/ProjectHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Friday, October 19, 2018 1:05:36 o'clock PM EDT
*/

public final class ProjectHolder implements org.omg.CORBA.portable.Streamable
{
  public Models.Corba.Project value = null;

  public ProjectHolder ()
  {
  }

  public ProjectHolder (Models.Corba.Project initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Models.Corba.ProjectHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Models.Corba.ProjectHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Models.Corba.ProjectHelper.type ();
  }

}
